### ISSUE TITLE
Format-Checklist incorrectly parses "Date" field from pipeline

### ISSUE THREAD

**Issue by zer0trust** [microsoft/Requirements#10]
```
PS C:\users\zer0trust\Desktop> $requirements | Invoke-Requirement | Format-Checklist
03:27:04 [   ] Add test.txt fileFormat-Checklist : Cannot bind parameter 'Date' to the target. Exception setting "Date": "Cannot convert null to type "System.DateTime"."
At line:1 char:38
+ $requirements | Invoke-Requirement | Format-Checklist
+                                      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Format-Checklist], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Format-Checklist
```

The "Date" field output from Invoke-Requirement has spaces in it. 

```
Date        : 7/1/2019 3:26:43 PM
Method      : Validate
State       : Stop
Result      : True
```

Modifying line 28 of formatters.ps1 as follows:

`$timestamp = Get-Date -Date "$_.Date" -Format 'hh:mm:ss'`

fixed the issue on my client.

**Comment by chriskuech** [comment]
I'm having trouble reproing this one. Can you try running `example.ps1` in the module root and seeing if you get any errors?

The `Date` field is actually a `datetime` not a `string`--the output you show implicitly calls `ToString()` which adds spaces.  I'm also confused how `$timestamp = Get-Date -Date "$_.Date" -Format 'hh:mm:ss'` is working for you--you can't string interpolate property references in PowerShell without wrapping the expression in `$(...)`, so I'm confused how `Get-Date` would actually be reading the date.  Also line 32 in `types.ps1` initializes the Date, so I'm not sure how it could be `$null`.

**Comment by zer0trust** [comment]
Clean session (it does seem to work the first time, but if I run it again, it generates the error below):

```
PS C:\WINDOWS\system32> $PSVersionTable.PSversion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  765


``
````
PS C:\WINDOWS\system32> $requirements | Invoke-Requirement | Format-Checklist
09:31:14 [   ] Add test.txt file
PS C:\WINDOWS\system32> $requirements | Invoke-Requirement | Format-Checklist
09:31:25 [   ] Add test.txt fileFormat-Checklist : Cannot bind parameter 'Date' to the target. Exception setting "Date": "Cannot convert null to type "System.DateTime"."
At line:1 char:38
+ $requirements | Invoke-Requirement | Format-Checklist
+                                      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Format-Checklist], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Format-Checklist
```

**Comment by chriskuech** [comment]
Is the repro for this the same as #9 ?  If so, I'm guessing its a duplicate because it's attempting to implicitly cast objects from the pipeline to `RequirementEvent`s and not finding the `Date` property.

**Comment by zer0trust** [comment]
Yes, basically the same steps.

**Comment by chriskuech** [comment]
OK closing as duplicate
