### ISSUE TITLE
Format-Checklist cosmetic error in the test output 

### ISSUE THREAD

**Issue by omiossec** [microsoft/Requirements#17]
While working on some examples with Requirements I have noticed that output for the test state in on the same line 

```
11:46:46 [   ] Create a folder for the app11:46:46 [   ] Create the json config File
```

```
$WebConfigRequirements = @(
    @{
        name = "AppFolder"
        describe = "Create a folder for the app" 
        test = {
            test-path -Path $AppPath
        }
        set = {
            new-item -path $AppPath -ItemType Directory
        }
    },
    @{
        name = "configfile"
        describe = "Create the json config File"
        test = {
            test-path -Path "$($AppPath)config.json"
        }
        set = {
            new-item -Path "$($AppPath)config.json"
        }
    }
)
$WebConfigRequirements | Invoke-Requirement | Format-Checklist
```` 
I will make some investigation on it

**Comment by chriskuech** [comment]
What terminal app/host do you use?  Also what powershell version?

**Comment by omiossec** [comment]
I use PowerShell core 6.2.1 on Windows 

Here's the script I use to reproduce 

```powershell
$ErrorActionPreference = "Stop"
Import-Module Requirements

$AppPath = "c:\work\dotnetbot1\"

$WebConfigRequirements = @(
    @{
        name = "AppFolder"
        describe = "Create a folder for the app" 
        test = {
            test-path -Path $AppPath
        }
        set = {
            new-item -path $AppPath -ItemType Directory
        }
    },
    @{
        name = "configfile"
        describe = "Create the json config File"
        test = {
            test-path -Path "$($AppPath)config.json"
        }
        set = {
            new-item -Path "$($AppPath)config.json"
        }
    }

)

$WebConfigRequirements | Invoke-Requirement | Format-Checklist
```
![image](https://user-images.githubusercontent.com/14043056/60907941-04664880-a27b-11e9-9bef-bd134b8ad42e.png)

As you can see the first time it works but for the second time no newline

it's the same with Windows PowerShell 5.1 on Windows 10 

![image](https://user-images.githubusercontent.com/14043056/60908093-5b6c1d80-a27b-11e9-8077-31fd0decadad.png)

If you had a requirement 
```powershell
@{
        name = "configfile-yaml"
        describe = "Create the yaml config File"
        test = {
            test-path -Path "$($AppPath)config.yaml"
        }
        set = {
            new-item -Path "$($AppPath)config.yaml"
        }
    }
``` 
it's worst 
![image](https://user-images.githubusercontent.com/14043056/60908196-98d0ab00-a27b-11e9-864b-0177c4b4b8dc.png)

I use the version 2.2.2 of the module

**Comment by chriskuech** [comment]
My top guess right now is that `Format-Checklist` has a bug where it only writes the green checkmark line if it `Set`s, so the `Test` text is never overwritten with a terminating newline.

I can look into this tonight.

**Comment by chriskuech** [comment]
So I confirmed my hypothesis, but I also identified more scenarios that are unaccounted for in the current implementation.  I will have to determine all the problematic scenarios and probably rewrite much of `Format-Checklist`.

**Comment by chriskuech** [comment]
Had a breakthrough and ended up only needing to add one more event handler.  This should be resolved now.
