### ISSUE TITLE
Format-Checklist exits PowerShell session on failing test

### ISSUE THREAD

**Issue by vuzzlevuzz** [microsoft/Requirements#42]
Getting a strange problem using format-checklist, if the test fails then the PowerShell session exits.  This is my first attempt at using this module but I'm sure nothing I'm doing should cause this?

Example code:
```
$requirements = @(
    @{
        Name     = "format-checklist-test"
        Describe = "Failing test exits session"
        Test     = { Test-Path ./sagsgsg }
    }
)

$requirements | invoke-requirement | format-checklist
```

> 07:46:15 [ X ] Failing test exits session

If the test is successful then it works fine, but if it fails then the PowerShell window closes after printing the result (I only managed to see the output by opening a second PowerShell session within the first one.)

I do not get the same problem when using format-callstack or no formatting at all.

Tested on 2 machines with same results
```

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> get-module requirements

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.2.6      requirements                        {Format-CallStack, Format-Checklist, Invoke-Requirement, New-Requirement...}
```

**Comment by chriskuech** [comment]
The `exit -1` needs to be removed.  Error should already be thrown in `Invoke-Requirement`, so the statement is pointless.

**Comment by vuzzlevuzz** [comment]
Now Format-Checklist and Format-Callstack are both broken :(

```
> $requirements | invoke-requirement | Format-Checklist
Format-Checklist : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
At line:1 char:38
+ $requirements | invoke-requirement | Format-Checklist
+                                      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (RequirementEvent:RequirementEvent) [Format-Checklist], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Format-Checklist

> $requirements | invoke-requirement | Format-CallStack
Format-CallStack : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.
At line:1 char:38
+ $requirements | invoke-requirement | Format-CallStack
+                                      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (RequirementEvent:RequirementEvent) [Format-CallStack], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Format-CallStack

> $requirements | invoke-requirement | Format-table

Date                Method State Result Requirement
----                ------ ----- ------ -----------
2019-09-24 13:24:49   Test Start        format-checklist-test
2019-09-24 13:24:49   Test  Stop False  format-checklist-test
```

**Comment by vuzzlevuzz** [comment]
Interestingly, if I run it from an elevated session it works

**Comment by chriskuech** [comment]
Sorry, I cannot repro on either 5.1 nor 6.2.3.  Can you make sure you only have the one version of Requirements installed, as well as ensure there are no stale autoloaded versions of the module in your session?

**Comment by vuzzlevuzz** [comment]
Ah, so sorry, it was an old session - my mistake.

I'm really enjoying the module but am finding quite a few issues (mostly minor) with format-checklist - I don't want to bombard you with issues so are you open to contributions?

**Comment by chriskuech** [comment]
Definitely create issues for any bugs you find and we can discuss details there.  Here are some factors that make me hesitant to accept changes to `Format-Checklist` without prior discussion:

* I just rewrote `Format-Checklist` and need to clean up the code a little (can do asap if necessary)
* We [do not have complete test cases](#44) and I am hesitant to make further changes until this is done for fear of more unnoticed regressions.
* `Format-Checklist` uses `Write-Host`, which is hacky and extremely hard to test with automation.  I have been considering more and more rewriting the printer to use `[Console]`
* I have a [big change planned](#35) that will require changes in basically all exposed functions.

**Comment by chriskuech** [comment]
I just pushed v2.3.0, so the API should be stable again if you want to contribute.
