### ISSUE TITLE
Push-Namespace not listed in FunctionsToExport in the PSD

### ISSUE THREAD

**Issue by FzzyBnny** [microsoft/Requirements#48]
The current version of the PSD lists the following:

    FunctionsToExport = @(
        'Format-Checklist',
        'Format-Verbose',
        'Invoke-Requirement',
        'New-Requirement',
        'Set-Requirement',
        'Test-Requirement'
    )

Note, Push-Namespace is not listed and thus not available when module is imported to a PS session. 

Unless this is currently intentional, recommend updating the PSD to the following so Push-Namespace is provided:

    FunctionsToExport = @(
        'Format-Checklist',
        'Format-Verbose',
        'Invoke-Requirement',
        'New-Requirement',
        'Set-Requirement',
        'Test-Requirement',
        'Push-Namespace'
    )

**Comment by chriskuech** [comment]
Thanks for reporting!

**Comment by FzzyBnny** [comment]
Thanks for resolving it!
