### ISSUE TITLE
Calling only tests (without applying)

### ISSUE THREAD

**Issue by Stephanevg** [microsoft/Requirements#60]
Hi guys,

For my use case, I would need to call the **test** blocks only of the requirements. I would still need to set them, but I would like to keep control of the action of **'setting'** and use the **test** functions to simply have an overview of the state of a machine, without necessarly applying the setting. 

Is that possible with this module? I looked and tried a bit, but I couldn't find it in the invoke-requirement parameter set. 
Perhaps, that could be a nice feature, having a `-TestsOnly` parameter or so .:)

**Comment by chriskuech** [comment]
You can find more functions in the module by running

```pwsh
(Get-Module Requirements).ExportedCommands
```

One of the other functions is `Test-Requirement` which works equivalently to your `-TestsOnly` parameter.
