### ISSUE TITLE
Is Remote execution viable use case?

### ISSUE THREAD

**Issue by gogbg** [microsoft/Requirements#71]
Is executing requirements on remote machine a viable use case for the tool?
For example extending the requirement schema with ComputerName and winrm connectivity details, so that the tool can orchestrate the execution on remote machines.

If so, I can contribute.

**Comment by FireHelmet** [comment]
Hi @gogbg ,

I'm a user of the module Requirements and I use the cmdlet [Invoke-Command](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command) another good module if you want to execute the scriptblock with another identity, look [Invoke-CommandAs](https://www.powershellgallery.com/packages/Invoke-CommandAs)

**Comment by chriskuech** [comment]
@gogbg, you can use [factory functions](https://github.com/microsoft/Requirements#reusable-requirements) to construct Requirements with whatever params you want.

**Comment by gogbg** [comment]
Thanks for the suggestions
