### ISSUE TITLE
Cannot validate argument on parameter when using Remote Variables

### ISSUE THREAD

**Issue by FireHelmet** [microsoft/Requirements#72]
Dear @chriskuech,

I use this requirement block :

`
@{
Describe = "Set Secret"
Test     = { Invoke-CommandAs -ComputerName $VmName -ScriptBlock { Get-SecretInfo -Name $Using:UserSecret } -AsSystem }
Set      = { Invoke-CommandAs -ComputerName $VmName -ScriptBlock { Set-Secret -Name $Using:UserSecret -Secret $Using:PasswordSecret -Vault CredManStore } -AsSystem }
}
`

But I get the error:

> Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and
then try the command again.
    + CategoryInfo          : InvalidData : (:) [Set-Secret], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.SecretManagement.SetSecretCommand
    + PSComputerName        : MYVMNAME

I already tried the same cmdlet without Requirements module and it works.

It seems the Remote Variables are not usable with Requirements, or is it a mistake from my side?

Thank you for your support!

**Comment by chriskuech** [comment]
I'm not sure the exact reason it's not working but likely due to how closures are constructed and invoked.  Best mitigation would be to add a `Param` block to your scriptblock and use `-ArgumentList` on `Invoke-Command`.

**Comment by FireHelmet** [comment]
@chriskuech ,

Thank you for your quick answer. Yes, I used the -ArgumentList and passed the variables as $args[x] like described [here](https://adamtheautomator.com/invoke-command/).
